server:
  port: 8099
  tomcat:
    basedir: /data/apps/temp



web:
 upload-path: /home/test/upload/


spring:
    datasource:
        name: mysql_test
        type: com.alibaba.druid.pool.DruidDataSource
        #druid相关配置
        druid:
          #监控统计拦截的filters
          filters: stat
          driver-class-name: com.mysql.jdbc.Driver
          #基本属性
          url: jdbc:mysql://47.99.122.206:3306/writer?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=
          #url: jdbc:mysql://127.0.0.1:3306/writer?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
          username: root
         # password: yf123456
          password: Aa123456
          #配置初始化大小/最小/最大
          initial-size: 1
          min-idle: 1
          max-active: 20
          #获取连接等待超时时间
          max-wait: 60000
          #间隔多久进行一次检测，检测需要关闭的空闲连接
          time-between-eviction-runs-millis: 60000
          #一个连接在池中最小生存的时间
          min-evictable-idle-time-millis: 300000
          validation-query: SELECT 'x'
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
          pool-prepared-statements: false
          max-pool-prepared-statement-per-connection-size: 20
    swagger:
           # 扫描的包路径,默认扫描所有
          base-package: com.winterchen
          enabled: true
    mail:
        host: smtp.qq.com
        username: 1140608363@qq.com
        password: ldzitjwxjwonbabh
        protocol: smtp #
        properties.mail.smtp.auth: true
        properties.mail.smtp.port: 465
        properties.mail.display.sendmail: Javen
        properties.mail.display.sendname: Spring Boot Guide Email
        properties.mail.smtp.starttls.enable: true
        properties.mail.smtp.starttls.required: true
        properties.mail.smtp.ssl.enable: true
        default-encoding: utf-8
        from: 1140608363@qq.com
    #文件上传相关
    thymeleaf:
        cache: false
    servlet:
        multipart.enabled: true
        multipart.location:
        multipart.max-file-size: 104857600 # 上传文件最大为 100M （默认值 1M 根据自身业务自行控制即可）
        multipart.max-request-size: 104857600 # 上传请求最大为 100M（默认值10M 根据自身业务自行控制即可）
        multipart.file-size-threshold: 0
        multipart.resolve-lazily: false
#    mvc:
#      static-path-pattern: /static/**

    jackson:
       date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

    mvc:
      static-path-pattern: /**
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,file:${web.upload-path}

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.winterchen.model



#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check


# 日志输出
logging:
    level:
       root: INFO
       com:
          winterchen: DEBUG
